<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Landing Page</title>
    <link rel="stylesheet" href="/landing.css">
</head>
<body>
<div class="button-bar">
    <a href="../login.jte" class="btn right">Log in</a>
</div>

<div class="header">
    <h2>StudyBuddy</h2>
</div>

<form action="../Login Page/index.html">
    <button class="start"><div id="bold">Start Learning</div></button>
</form>
<div class="descriptions">
    <div class="description-box">
        <div id="bold">Learn with AI</div>
        AI helps you study with curated quizzes and flashcards
    </div>
    <div class="description-box">
        <div id="bold">How-To</div>
        Upload lecture slides and notes to focus on a topic
    </div>
</div>

<div class="howto">
    <div class="howtobox">
        <div id="bold">1.Upload a file from class</div>
        <img src="../images/upload.png" alt="Upload" class="howtoimg" />
    </div>

    <div class="howtobox">
        <div id="bold">2.Practice with flashcards</div>
        <img src="../images/flashcards.png" alt="Flashcards" class="howtoimg" />
    </div>

    <div class="howtobox">
        <div id="bold">3.Take a quiz to test your knowledge</div>
        <img src="../images/quiz.png" alt="Quiz" class="howtoimg" />
    </div>
</div>

</body>
</html>