<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
success
<br>
<a href="http://localhost:8080/testflashcards">test flashcards</a>
<br>
<a href="http://localhost:8080/testquizzes">test quizzes</a>
<br>
<a href="http://localhost:8080/studysets">show sets</a>
</body>
</html>